version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
    timezone: Europe/Zurich
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nodemon
    versions:
    - 2.0.6
